# "#" this is a comment
#specifying version according to docker engine release version
#for version refer to https://docs.docker.com/compose/compose-file/

version: "3.7"

#making sevices
services:
        #First service app
        chat:
                build:
                        #location of Dockerfile
                        context: ./mattermost
                        network: "host"
                        #name of the dockerfile
                        dockerfile: Dockerfile
                network_mode: "host"
                volumes:
                        - "./mattermost:/mattermost"
                labels:
                        com.oxapp.description: "Chat App"
        #second app
        mail:
                build:
                        context: ./rainloop
                        dockerfile: Dockerfile
                ports:
                        - "8075:80"
                labels:
                        com.example.description: "Mailing App"
        #third app
        activemq:
                build:
                        context: ./activemq
                        dockerfile: Dockerfile
                network_mode: "host"
                labels:
                        com.oxapp.description: "Apache Activemq"
