version: '3.5'
services:
    zf:
        build: 
            context: ./api/v1/docker
        depends_on:
            - wf   
        ports:
            - "8080:80"
        volumes:
            - ./:/app
            - /tmp:/tmp
    wf:
        build: 
            context: ./integrations/workflow
        network_mode: "host"    
        ports:
            - "8090:8090"
        volumes:
            - ./:/app
            - /tmp:/tmp    
    vw:
        build: 
            context: ./view/docker
        depends_on:
            - zf    
        network_mode: "host"    
        ports:
            - "8081:8081" 
        volumes:
            - ./:/app
            - /tmp:/tmp               