server:
  port: 8085
flyway:
  baseline-on-migrate: true
spring:
  activemq:
    broker-url: tcp://172.16.1.141:61616
    user: admin
    password: admin
  quartz:
    properties:
      org:
        quartz:
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: false
            misfireThreshold: 60000
            tablePrefix: QRTZ_
            useProperties: true
          plugin:
            shutdownHook:
              class: org.quartz.plugins.management.ShutdownHookPlugin
              cleanShutdown: true
          threadPool:
            threadCount: 20
    jdbc:
      initialize-schema: never
    job-store-type: jdbc
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    platform: org.hibernate.dialect.MySQL5Dialect
    url: jdbc:mysql://172.16.1.141:3306/quartz_db?useSSL=false
    username: root
    password: purvi08
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
smtp:
  host: localhost
  port: 25
  username: ""
  password: ""
  from:
    email: support@eoxvantage.com
db:
  host: jdbc:mysql://172.16.1.141/appBuilder_oxzionapi
  user: root
  password: purvi08
contentType: text/html
camel:
  component:
    enabled: true
    websocket:
      enabled: true
      host: localhost
      port: 8081
apikey: 0cb6fd4c-40a5-11e9-a30d-1c1b0d785c98
authorization-url: http://172.16.1.141:8080/auth
elastic:
  host: localhost
  port: 9200