server:
  port: 8085
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  quartz:
    properties:
      org:
        quartz:
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: false
            misfireThreshold: 60000
            tablePrefix: QRTZ_
            useProperties: true
          plugin:
            shutdownHook:
              class: org.quartz.plugins.management.ShutdownHookPlugin
              cleanShutdown: true
          threadPool:
            threadCount: 20
    jdbc:
      initialize-schema: never
    job-store-type: jdbc
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: password
    platform: org.hibernate.dialect.MySQL5Dialect
    url: jdbc:mysql://localhost:3306/quartz_demo_db
    username: root
  jpa:
    open-in-view: false
    show-sql: true
smtp:
  host: localhost
  port: 25
  username: bharatgoku@gmail.com
  password: goku7569
  from:
    email: bharatgoku@gmail.com
contentType: text/html
camel:
  component:
    enabled: true
    websocket:
      enabled: true
      host: localhost
      port: 8081
websocket:
  port: 8081
  host: localhost
  channel: notification
apikey: 0cb6fd4c-40a5-11e9-a30d-1c1b0d785c98
authorization-url: http://localhost:8080/auth
