version: '3.5'
services:
    zf:
        build: 
            context: ./docker
            dockerfile: Dockerfile
        ports:
            - "8080:80"
            - "8081:8081"
        volumes:
            - ../..:/app
            - /tmp:/tmp
