version: '3.5'
services:
    zf:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
        