version: '3.5'
services:
    zf:
        build: 
            context: ./docker
            dockerfile: Dockerfile
        environment:
            XDEBUG_CONFIG: remote_host=localhost remote_port=9000 remote_enable=1
        ports:
            - "8080:80"
        volumes:
            - ../..:/app
            - /tmp:/tmp
