app:
    -
        name: ArrowHead
        uuid: da8f0152-b8d3-43bf-8090-40103bb98d5e
        description: 'App for Arrow Head'
        category: EXAMPLE_CATEGORY
        type: 2
        autostart: true
org:
    -
        name: ArrowHead
        uuid: 34bf01ab-79ca-42df-8284-965d8dbf290e
        email: admin@arrowhead.com
        address1: '6 bCenterpoint'
        address2: Dr.
        city: 'La Palma'
        state: CA
        zip: 90623
        country: 'United States'
        contact:
            username: arrowheadAdmin
            firstname: Admin
            lastname: User
            email: admin@arrowhead.com
        preferences: '{}'
privilege:
    -
        name: MANAGE_POLICY_APPLICATION
        permission: 3
    -
        name: MANAGE_APPLICATION_EXPORT
        permission: 3
role:
    -
        name: Agent
        default: true
        privileges:
            -
                privilege_name: MANAGE_POLICY_APPLICATION
                permission: 3
            -
                privilege_name: MANAGE_APPLICATION_EXPORT
                permission: 3
        uuid: 77a1d830-c016-4849-802e-a80117c43c2a
entity:
    -
        name: 'Dealer Policy'
        override_data: true
        field:
            -
                name: status
                text: Status
                index: true
                data_type: text
            -
                name: documents
                text: Documents
                data_type: document
pages:
    -
        page_name: AgentHomePage.yml
        uuid: dce7df02-7a3b-4468-bed8-edffd8216822
    -
        page_name: ExportWorkbook.yml
        uuid: 219b3a85-7901-4360-9a73-09ed6a659a1d
menu:
    -
        name: Home
        icon: 'fas fa-home'
        page_uuid: dce7df02-7a3b-4468-bed8-edffd8216822
        uuid: 2ba0936d-94d1-4b68-9da2-ccc60faaefe0
        privilege: MANAGE_POLICY_APPLICATION_READ
    -
        name: 'Export Workbooks'
        icon: 'fad fa-book'
        page_uuid: 219b3a85-7901-4360-9a73-09ed6a659a1d
        uuid: 6d768db0-6e99-4480-819f-8f3522b99b5d
        privilege: MANAGE_APPLICATION_EXPORT_READ
form:
    -
        name: 'DealerWorkbook Form'
        uuid: 280dbc6d-638e-4fba-9095-8430c226ec7b
        description: 'Dealer Workbook form to generate carrier templates'
        template_file: dealerWorkbook.json
        entity: 'Dealer Policy'
job:
    -
        uuid: 3d040d2b-4cdc-4ecb-a06f-235b2740e596
        name: 'Trigger Template Generation'
        url: /app/da8f0152-b8d3-43bf-8090-40103bb98d5e/delegate/TriggerTemplateService
        cron: '30000 * * * * ? *'
        data:
            orgId: 34bf01ab-79ca-42df-8284-965d8dbf290e
            appId: da8f0152-b8d3-43bf-8090-40103bb98d5e
            entityName: 'Dealer Policy'
