app:
    -
        name: ArrowHead
        uuid: da8f0152-b8d3-43bf-8090-40103bb98d5e
        description: 'App for Arrow Head'
        category: EXAMPLE_CATEGORY
        type: 2
        autostart: true
org:
    -
        name: ArrowHead
        uuid: 34bf01ab-79ca-42df-8284-965d8dbf290e
        email: arrowhead@gmail.com
        address1: '6 bCenterpoint'
        address2: Dr.
        city: 'La Palma'
        state: CA
        zip: 90623
        country: 'United States'
        contact:
            username: arrowhead.gmail.com
            firstname: Admin
            lastname: User
            email: arrowhead@gmail.com
        preferences: '{}'
privilege:
    -
        name: MANAGE_POLICY_APPROVAL
        permission: 3
    -
        name: MANAGE_MY_POLICY
        permission: 3
    -
        name: MANAGE_ADMIN
        permission: 3
role:
    -
        name: Dealer
        default: true
        privileges:
            -
                privilege_name: MANAGE_MY_POLICY
                permission: 3
        uuid: 77a1d830-c016-4849-802e-a80117c43c2a
    -
        name: Admin
        privileges:
            -
                privilege_name: MANAGE_POLICY_APPROVAL
                permission: 3
        uuid: 55a79619-5d7e-432a-9913-ec044906db03
entity:
    -
        name: Workbook
        field:
            -
                name: status
                text: Status
                data_type: text
            -
                name: documents
                text: Documents
                data_type: document
pages:
    -
        page_name: UserHomePage.yml
        uuid: dce7df02-7a3b-4468-bed8-edffd8216822
    -
        page_name: Manageworkbooks.yml
        uuid: 4dfdb763-772c-4ed5-8e0d-324262f7bb86
menu:
    -
        name: Home
        icon: 'fa fa-home'
        page_uuid: dce7df02-7a3b-4468-bed8-edffd8216822
        uuid: 2ba0936d-94d1-4b68-9da2-ccc60faaefe0
        privilege: MANAGE_MY_POLICY_READ
    -
        name: 'Manage Workbooks'
        icon: 'fa fa-book'
        page_uuid: 4dfdb763-772c-4ed5-8e0d-324262f7bb86
        uuid: fcbca321-4c39-4dd2-97bf-45b734bbabde
        privilege: MANAGE_POLICY_APPROVAL_READ
form:
    -
        name: 'General Information'
        uuid: a8f015fa-2dcb-4806-8ec0-ca5847c1c471
        description: 'Page General Info'
        template_file: generalInformation.json
        entity: Workbook
