app:
    -
        name: ArrowHead
        uuid: da8f0152-b8d3-43bf-8090-40103bb98d5e
        description: 'App for Arrow Head'
        category: EXAMPLE_CATEGORY
        type: 2
        autostart: true
org:
    -
        name: ArrowHead
        uuid: 34bf01ab-79ca-42df-8284-965d8dbf290e
        email: arrowhead@gmail.com
        address1: '6 bCenterpoint'
        address2: Dr.
        city: 'La Palma'
        state: CA
        zip: 90623
        country: 'United States'
        contact:
            username: arrowhead.gmail.com
            firstname: Admin
            lastname: User
            email: arrowhead@gmail.com
        preferences: '{}'
privilege:
    -
        name: MANAGE_POLICY_APPLICATION
        permission: 3
    -
        name: MANAGE_APPLICATION_EXPORT
        permission: 3
role:
    -
        name: Agent
        default: true
        privileges:
            -
                privilege_name: MANAGE_POLICY_APPLICATION
                permission: 3
            -
                privilege_name: MANAGE_APPLICATION_EXPORT
                permission: 3
        uuid: 77a1d830-c016-4849-802e-a80117c43c2a
entity:
    -
        name: 'Dealer Policy'
        fieldReference: DealerPolicyFields.xlsx
        field:
            -
                name: status
                text: Status
                data_type: text
            -
                name: documents
                text: Documents
                data_type: document
pages:
    -
        page_name: AgentHomePage.yml
        uuid: dce7df02-7a3b-4468-bed8-edffd8216822
    -
        page_name: ExportWorkbook.yml
        uuid: 219b3a85-7901-4360-9a73-09ed6a659a1d
menu:
    -
        name: Home
        icon: 'fas fa-home'
        page_uuid: dce7df02-7a3b-4468-bed8-edffd8216822
        uuid: 2ba0936d-94d1-4b68-9da2-ccc60faaefe0
        privilege: MANAGE_POLICY_APPLICATION_READ
    -
        name: 'Export Workbooks'
        icon: 'fad fa-book'
        page_uuid: 219b3a85-7901-4360-9a73-09ed6a659a1d
        uuid: 6d768db0-6e99-4480-819f-8f3522b99b5d
        privilege: MANAGE_APPLICATION_EXPORT_READ
form:
    -
        name: 'Consolidated Form'
        uuid: 2b4a5099-4a2b-415a-b1d1-b539cbe1eee7
        description: 'Consolidated Wiz'
        template_file: consolidatedWizard.json
        entity: 'Dealer Policy'
