app:
    -
        name: Transportation
        uuid: 103c128a-1553-498b-8f37-cd3e16c56857
        description: Transportation
        category: Dashboards
        type: 2
        autostart: 'false'
org:
    -
        name: 'EOX Vantage1'
        uuid: b0923de7-0387-48ea-8f29-5d3704d96a46
        email: helpdesk@vantageagora.com
        address1: '23611 Chagrin Blvd'
        address2: 'Ste 320, Beachwood, Ohio 44122'
        city: Beachwood
        state: OH
        zip: 44122
        contact:
            username: supportadmin
            firstname: Support
            lastname: Admin
            email: helpdesk@vantageagora.com
        preferences:
            currency: USD
            timezone: America/New_York
            dateformat: mm/dd/yy
        country: 'United States'
privilege:
    -
        name: MANAGE_TRANSPORTATION
        permission: 15
role:
    -
        name: 'Transportation Manager'
        default: true
        privileges:
            -
                privilege_name: MANAGE_TRANSPORTATION
                permission: 15
        uuid: 11560dc4-dfb8-4e48-a7f7-bfa4054c88c6
pages:
    -
        page_name: availableloadsreport.yml
        uuid: 68b97b51-c68d-4678-8b5b-07b6dbb7057e
    -
        page_name: trailercurrentlocation.yml
        uuid: bdcf93cb-b63b-4e57-adea-ce5b6d25cea7
    -
        page_name: tripsummary.yml
        uuid: 1c8eb1e5-f5ec-4af9-88e6-d17eca54d8e4
    -
        page_name: monthlymileagereport.yml
        uuid: 46bd5754-62d7-4a80-a7a0-8d97131d7cb8
    -
        page_name: monthlyrevenuesummary.yml
        uuid: d2c3a908-465b-4468-8ba7-d51eadd93e6a
    -
        page_name: payperiodsummary.yml
        uuid: 20633819-40e6-45de-b123-eef2772f2503
    -
        page_name: unbilledrevenue.yml
        uuid: fec34db0-3d69-46dc-af75-f794fa4e3ad1
    -
        page_name: RevenuevsPay.yml
        uuid: c643663f-4c40-4298-bd6e-3fafdd65ceca
menu:
    -
        name: 'Available Loads'
        icon: 'fa fa-road'
        privilege: MANAGE_TRANSPORTATION_WRITE
        page_uuid: 68b97b51-c68d-4678-8b5b-07b6dbb7057e
        uuid: 218b1966-d94d-42fa-b4e4-c8518f088493
    -
        name: 'Trailer Current Location'
        icon: 'fa fa-map'
        privilege: MANAGE_TRANSPORTATION_WRITE
        page_uuid: bdcf93cb-b63b-4e57-adea-ce5b6d25cea7
        uuid: c3b1d64e-b61d-4f5e-8807-d34cd6a9c868
    -
        name: 'Trip Summary'
        icon: 'fa fa-university'
        privilege: MANAGE_TRANSPORTATION_WRITE
        page_uuid: 1c8eb1e5-f5ec-4af9-88e6-d17eca54d8e4
        uuid: 6a288707-b121-4b99-874d-b682c01cca56
    -
        name: 'Monthly Mileage'
        icon: 'fa fa-usd'
        privilege: MANAGE_TRANSPORTATION_WRITE
        page_uuid: 46bd5754-62d7-4a80-a7a0-8d97131d7cb8
        uuid: 7da49137-324a-477d-94d0-7b566e6274c7
    -
        name: 'Monthly Revenue'
        icon: 'fa fa-usd'
        privilege: MANAGE_TRANSPORTATION_WRITE
        page_uuid: d2c3a908-465b-4468-8ba7-d51eadd93e6a
        uuid: 936b6dfe-d704-4dc8-8acb-ec6582054759
    -
        name: 'Pay Period'
        icon: 'fa fa-credit-card-alt'
        privilege: MANAGE_TRANSPORTATION_WRITE
        page_uuid: 20633819-40e6-45de-b123-eef2772f2503
        uuid: 2a288707-c121-4c99-874d-b282e01cca34
    -
        name: 'Unbilled Revenue'
        icon: 'fa fa-money'
        privilege: MANAGE_TRANSPORTATION_WRITE
        page_uuid: fec34db0-3d69-46dc-af75-f794fa4e3ad1
        uuid: 6a285707-b541-4b99-874d-b682c01cca56
    -
        name: 'Revenue v.s Pay'
        icon: 'fa fa-money'
        privilege: MANAGE_TRANSPORTATION_WRITE
        page_uuid: c643663f-4c40-4298-bd6e-3fafdd65ceca
        uuid: 639a1d83-b01c-49c0-a91a-f3d60f1280b1