app:
    -
        name: DiveInsurance
        uuid: d77ea120-b028-479b-8c6e-60476b6a4456
        description: 'App for Dive Insurance'
        category: EXAMPLE_CATEGORY
        type: 2
        autostart: true
org:
    -
        name: 'Vincencia & Buckley'
        uuid: f0033dc0-126b-40ba-89e0-d3061bdeda4c
        email: testhub07@gmail.com
        address1: '6 bCenterpoint'
        address2: Dr.
        city: 'La Palma'
        state: CA
        zip: 90623
        country: 'United States'
        contact:
            username: testhub07.gmail.com
            firstname: Admin
            lastname: User
            email: testhub07@gmail.com
        preferences: '{}'
privilege:
    -
        name: MANAGE_POLICY_APPROVAL
        permission: 3
    -
        name: MANAGE_MY_POLICY
        permission: 3
    -
        name: MANAGE_DIVEINSURANCE_ERRORS
        permission: 3
role:
    -
        name: 'Policy Holder'
        default: true
        privileges:
            -
                privilege_name: MANAGE_MY_POLICY
                permission: 3
        uuid: 703d3a09-b7f3-49e9-9c79-74d5cae7f6e7
    -
        name: CSR
        privileges:
            -
                privilege_name: MANAGE_POLICY_APPROVAL
                permission: 3
        uuid: 41bd1503-20c8-49fc-be10-6c9a8222489c
entity:
    -
        name: 'Individual Professional Liability'
        field:
            -
                name: policyStatus
                text: 'Policy Status'
                data_type: text
            -
                name: documents
                text: 'Policy Documents'
                data_type: document
    -
        name: 'Dive Store'
        field:
            -
                name: policyStatus
                text: 'Policy Status'
                data_type: text
            -
                name: documents
                text: 'Policy Documents'
                data_type: document
    -
        name: 'Dive Boat'
        field:
            -
                name: policyStatus
                text: 'Policy Status'
                data_type: text
            -
                name: documents
                text: 'Policy Documents'
                data_type: document
    -
        name: 'Emergency First Response'
        field:
            -
                name: policyStatus
                text: 'Policy Status'
                data_type: text
            -
                name: documents
                text: 'Policy Documents'
                data_type: document
    -
        name: 'Pocket Card Job'
        field:
            -
                name: jobStatus
                text: 'Job Status'
                data_type: text
            -
                name: documents
                text: 'Pocket Card'
                data_type: document
pages:
    -
        page_name: UserHomePage.yml
        uuid: c718e435-efc4-4677-ba72-4b8996b78a64
    -
        page_name: UserHistoryPage.yml
        uuid: e0a85518-7657-470f-92d8-00b3dea0bcf4
    -
        page_name: CSRDashboardPage.yml
        uuid: 016a34e6-4af6-4863-b8e2-0cee142b09a2
    -
        page_name: CSRRequestsPage.yml
        uuid: 9b52ced7-80b7-4cd6-a986-d4df6812b139
    -
        page_name: ErrorHandlerPage.yml
        uuid: 3af8eeb0-7f43-422a-90f4-2b30b7aab9b7
    -
        page_name: CSRManagePolicyPage.yml
        uuid: a488af79-31ee-4f11-8715-5bec00f85c8d
    -
        page_name: CSRSearchPage.yml
        uuid: 38b1b9c7-0f6e-4e80-bb08-63262e56c2f9
    -
        page_name: VerifyPadiPage.yml
        uuid: 0c17785a-b7ae-46c4-a1c3-8bed234b4482
    -
        page_name: PocketCardPage.yml
        uuid: 11cd5446-c2fa-42cc-93b1-638670f4adf7
    -
        page_name: MyAssignmentsPage.yml
        uuid: 151ba91d-f17a-4034-a25f-86f108594637
menu:
    -
        name: Home
        privilege: MANAGE_MY_POLICY_WRITE
        icon: 'fa fa-home'
        page_uuid: c718e435-efc4-4677-ba72-4b8996b78a64
        uuid: 7794c91e-b708-41be-83e1-cc0bb6cd667a
    -
        name: 'My History'
        privilege: MANAGE_MY_POLICY_READ
        icon: 'fa fa-book'
        page_uuid: e0a85518-7657-470f-92d8-00b3dea0bcf4
        uuid: 623132d9-8ccb-4c8a-b7b7-a3b0921defdc
    -
        name: 'Approval Request'
        privilege: MANAGE_MY_POLICY_WRITE
        icon: 'fa fa-list'
        page_name: UserApprovalRequest.yml
        uuid: 7794c91e-b708-41be-83e1-cc0bb6cd789e
    -
        name: Home
        icon: 'fa fa-home'
        privilege: MANAGE_POLICY_APPROVAL_READ
        page_uuid: 016a34e6-4af6-4863-b8e2-0cee142b09a2
        uuid: 24176975-8f4d-499d-8b2d-86902de26c14
    -
        name: Requests
        privilege: MANAGE_POLICY_APPROVAL_WRITE
        icon: 'fa fa-list'
        page_uuid: 9b52ced7-80b7-4cd6-a986-d4df6812b139
        uuid: 50fd8782-3e08-4a4c-9ff2-10d404904e5e
    -
        name: Errors
        privilege: MANAGE_DIVEINSURANCE_ERRORS_WRITE
        icon: 'fa fa-warning'
        page_uuid: 3af8eeb0-7f43-422a-90f4-2b30b7aab9b7
        uuid: 41551bff-e30e-4ba5-abc1-1a864f12e061
    -
        name: 'Manage Policies'
        icon: 'fa fa-folder-open'
        privilege: MANAGE_POLICY_APPROVAL_WRITE
        page_uuid: a488af79-31ee-4f11-8715-5bec00f85c8d
        uuid: 576f6ce4-74e6-11ea-bc55-0242ac130003
    -
        name: 'Search Policies'
        icon: 'fa fa-search'
        privilege: MANAGE_POLICY_APPROVAL_WRITE
        page_uuid: 38b1b9c7-0f6e-4e80-bb08-63262e56c2f9
        uuid: 3a4cc987-5627-4882-89ae-3bdc4f6e1e77
    -
        name: 'Verify PADI details'
        icon: 'fa fa-list-alt'
        privilege: MANAGE_POLICY_APPROVAL_READ
        page_uuid: 0c17785a-b7ae-46c4-a1c3-8bed234b4482
        uuid: 9bf92403-2111-4d05-9d89-01a609ed4b83
    -
        name: 'Pocket Card'
        privilege: MANAGE_POLICY_APPROVAL_WRITE
        icon: 'fa fa-address-card'
        page_uuid: 11cd5446-c2fa-42cc-93b1-638670f4adf7
        uuid: 7794c91e-b708-41be-83e1-cc0bb6cd669a
    -
        name: MyAssignments
        privilege: HIDE_FOR_NOW
        icon: 'fa fa-list'
        page_uuid: 151ba91d-f17a-4034-a25f-86f108594637
        uuid: 3b396d26-c0cb-4436-8804-f22431d6ac8c
workflow:
    -
        name: 'Dive Boat'
        uuid: bb15e393-11b9-48ea-bc5a-5b7616047cb1
        bpmn_file: 'Dive Boat/NewApplicationSubmission.bpmn'
        entity: 'Dive Boat'
    -
        name: 'Dive Boat Endorsement'
        uuid: 2bc1caaa-9628-486d-8b42-104534625993
        bpmn_file: 'Dive Boat/DiveBoatEndorsement.bpmn'
        entity: 'Dive Boat'
form:
    -
        name: 'PADI Verification'
        uuid: d2ed4200-9131-4671-b0e0-de3e27c3f610
        description: 'Page for CSR to verify PADI details'
        template_file: padiValidationPage.json
        entity: Padi
    -
        name: 'Pocket Card'
        uuid: e2ed4200-9131-4671-b0e0-de3e27c3f611
        description: 'Lets CSR generate and view Pocket Cards'
        template_file: pocketCard.json
        entity: 'Pocket Card Job'
group:
    reactivate: null
    status: null
    org_id: (optional)
    name: null
    parent_id: (optional)
    manager_id: null
