app:
    -
        name: DiveInsurance
        uuid: d77ea120-b028-479b-8c6e-60476b6a4456
        description: 'App for Dive Insurance'
        category: EXAMPLE_CATEGORY
        type: 2
        autostart: 'true'
org:
    -
        name: 'Vincencia & Buckley'
        uuid: c1ed4200-9131-4671-b0e0-de3e27c3f609
        email: testhub07@gmail.com
        address1: '6 bCenterpoint'
        address2: Dr.
        city: 'La Palma'
        state: CA
        zip: 90623
        country: 'United States'
        contact:
            username: testhub07.gmail.com
            firstname: Admin
            lastname: User
            email: testhub07@gmail.com
        preferences: '{}'
privilege:
    -
        name: MANAGE_POLICY_APPROVAL
        permission: 3
    -
        name: MANAGE_MY_POLICY
        permission: 3
role:
    -
        name: 'Policy Holder'
        default: true
        privileges:
            -
                privilege_name: MANAGE_MY_POLICY
                permission: 3
        uuid: fa31149b-2f01-445a-bc24-7843196bd964
menu:
    -
        name: Home
        privilege: MANAGE_MY_POLICY_WRITE
        icon: 'fa fa-home'
        page:
            name: 'My Policies'
            description: 'Shows a list of users policies'
            content:
                -
                    type: Document
                    content: '<p><h2>Personal Policies</h2></p><p></p>'
                -
                    type: List
                    content:
                        route: file
                        filterable: true
                        reorderable: true
                        resizable: true
                        pageable:
                            buttonCount: 3
                            pageSizes:
                                - 10
                                - 20
                                - 50
                            info: true
                        actions:
                            -
                                name: View
                                page_id: '1'
                                icon: 'fa fa-envelope-open'
                            -
                                name: Cancel
                                page_id: '3'
                                icon: 'fa fa-window-close'
                        columnConfig:
                            -
                                title: Name
                                field: name
                            -
                                title: Status
                                field: status
                            -
                                title: Data
                                field: data
        uuid: 8afee66e-21e5-49c3-b566-b1a248d7cadb
    -
        name: 'My History'
        privilege: MANAGE_MY_POLICY_READ
        icon: 'fa fa-table'
        page:
            name: 'All Policies'
            description: 'Shows all the policies'
            content:
                -
                    type: List
                    content:
                        route: file
        uuid: d988d72f-8c54-4d41-93f8-cbccafcdd1e7
    -
        name: 'Verify PADI details'
        icon: 'fa fa-search'
        page:
            name: 'Verify PADI details'
            description: 'Lets CSR to input and check PADI Data'
            content:
                -
                    content: '<h3>Verify PADI Details</h3>'
                    type: Document
                -
                    formUuid: d2ed4200-9131-4671-b0e0-de3e27c3f610
                    type: Form
        uuid: 23b203bc-c1e0-482d-8836-8ec02bc6f2e1
    -
        name: Home
        icon: 'fa fa-paper'
        privilege: MANAGE_POLICY_APPROVAL_READ
        page:
            name: Dashboard
            description: 'Shows dashboard'
            content:
                -
                    type: Dashboard
                    dashboard: Dashboard
        uuid: 3dc74e92-7a90-492e-83fe-ce65bb412aaa
    -
        name: Requests
        privilege: MANAGE_POLICY_APPROVAL_WRITE
        icon: 'fa fa-help'
        page:
            name: Requests
            description: 'Shows requests'
            content:
                -
                    type: List
                    content:
                        route: assignments
                        filterable: true
                        reorderable: true
                        resizable: true
                        sortable: true
                        pageable:
                            buttonCount: 3
                            pageSizes:
                                - 10
                                - 20
                                - 50
                            info: true
                        actions:
                            -
                                name: Approve
                                rule: '{{to_be_claimed}} == 1'
                                details:
                                    - { type: Update, url: 'workflowinstance/{{workflowInstanceId}}/activityinstance/{{activityInstanceId}}/claim' }
                                    - { type: Form, url: 'workflowinstance/{{workflowInstanceId}}/activityinstance/{{activityInstanceId}}/form' }
                                icon: 'fa fa-plus-circle'
                            -
                                name: Approve
                                rule: '{{to_be_claimed}} == 0'
                                details:
                                    - { type: 'Form"', url: 'workflowinstance\/{{workflowInstanceId}}\/activityinstance\/{{activityInstanceId}}\/form"' }
                        columnConfig:
                            -
                                title: PADI
                                field: padi
                            -
                                title: 'First Name'
                                field: first_name
                            -
                                title: 'Last Name'
                                field: last_name
                            -
                                title: Product
                                field: workflow_name
                            -
                                title: Task
                                field: activityName
                            -
                                title: 'Submission Date'
                                field: start_date
        uuid: c6be57db-299b-4da5-900f-63dd134f286c
    -
        name: 'Manage Policies'
        icon: 'fa fa-list'
        privilege: MANAGE_POLICY_APPROVAL_WRITE
        page:
            name: 'Manage Policies'
            description: 'Page to manage policies'
            content:
                -
                    type: List
                    content:
                        route: ''
        uuid: 46e296fd-87ef-4aa2-9c35-9b4e77f539b8
workflow:
    -
        name: 'Individual Liability'
        uuid: f0efea9e-7863-4368-a9b2-baa1a1603067
        bpmn_file: 'Individual Professional Liability/NewUserApplicationSubmission.bpmn'
        entity: 'Individual Professional Liability'
    -
        name: 'Dive Store'
        uuid: cb99e634-de00-468d-9230-d6f77d241c5b
        bpmn_file: 'Dive Store/NewApplication.bpmn'
        entity: 'Dive Store'
    -
        name: 'Dive Boat'
        uuid: bb15e393-11b9-48ea-bc5a-5b7616047cb1
        bpmn_file: 'Dive Boat/NewApplicationSubmission.bpmn'
        entity: 'Dive Boat'
    -
        name: 'Individual Liability Auto Renewal'
        uuid: 91cb9e10-5845-4379-97c9-f9486b702bd6
        bpmn_file: 'Individual Professional Liability/IPLAutoRenewal.bpmn'
        entity: 'Individual Professional Liability'
form:
    -
        name: 'PADI Verification'
        uuid: d2ed4200-9131-4671-b0e0-de3e27c3f610
        description: description
        template: 'JSON STRING'
        entity: Padi
job:
    -
        import_padi:
            -
                stored_procedure_name: ox_padi_verification
                upload_host_name: 206.107.76.164
                upload_host_user: vbinsurance
                upload_user_password: '<<InsureName>>'
