app:
    -
        name: DiveInsurance
        uuid: d77ea120-b028-479b-8c6e-60476b6a4456
        description: 'App for Dive Insurance'
        category: EXAMPLE_CATEGORY
        type: 2
        autostart: true
org:
    -
        name: 'Vincencia & Buckley'
        uuid: f0033dc0-126b-40ba-89e0-d3061bdeda4c
        email: testhub07@gmail.com
        address1: '6 bCenterpoint'
        address2: Dr.
        city: 'La Palma'
        state: CA
        zip: 90623
        country: 'United States'
        contact:
            username: testhub07.gmail.com
            firstname: Admin
            lastname: User
            email: testhub07@gmail.com
        preferences: '{}'
privilege:
    -
        name: MANAGE_POLICY_APPROVAL
        permission: 3
    -
        name: MANAGE_MY_POLICY
        permission: 3
    -
        name: MANAGE_DIVEINSURANCE_ERRORS
        permission: 3
    -
        name: MANAGE_ADMIN
        permission: 3
role:
    -
        name: 'Policy Holder'
        default: true
        privileges:
            -
                privilege_name: MANAGE_MY_POLICY
                permission: 3
        uuid: 703d3a09-b7f3-49e9-9c79-74d5cae7f6e7
    -
        name: CSR
        privileges:
            -
                privilege_name: MANAGE_POLICY_APPROVAL
                permission: 3
        uuid: 41bd1503-20c8-49fc-be10-6c9a8222489c
entity:
    -
        name: 'Individual Professional Liability'
        field:
            -
                name: policyStatus
                text: 'Policy Status'
                data_type: text
                index: true
            -
                name: documents
                text: 'Policy Documents'
                data_type: document
            -
                name: start_date
                data_type: date
                index: true
            -
                name: end_date
                data_type: date
                index: true
            -
                name: firstname
                data_type: text
                index: true
            -
                name: lastname
                data_type: text
                index: true
            -
                name: padi
                data_type: text
                index: true
            -
                name: product
                data_type: text
                index: true
    -
        name: 'Dive Store'
        field:
            -
                name: policyStatus
                text: 'Policy Status'
                data_type: text
                index: true
            -
                name: documents
                text: 'Policy Documents'
                data_type: document
            -
                name: start_date
                data_type: date
                index: true
            -
                name: end_date
                data_type: date
                index: true
            -
                name: firstname
                data_type: text
                index: true
            -
                name: lastname
                data_type: text
                index: true
            -
                name: padi
                data_type: text
                index: true
            -
                name: product
                data_type: text
                index: true
    -
        name: 'Dive Boat'
        field:
            -
                name: policyStatus
                text: 'Policy Status'
                data_type: text
                index: true
            -
                name: documents
                text: 'Policy Documents'
                data_type: document
            -
                name: start_date
                data_type: date
                index: true
            -
                name: end_date
                data_type: date
                index: true
            -
                name: firstname
                data_type: text
                index: true
            -
                name: lastname
                data_type: text
                index: true
            -
                name: padi
                data_type: text
                index: true
            -
                name: product
                data_type: text
                index: true
    -
        name: 'Emergency First Response'
        field:
            -
                name: policyStatus
                text: 'Policy Status'
                data_type: text
                index: true
            -
                name: documents
                text: 'Policy Documents'
                data_type: document
            -
                name: start_date
                data_type: date
                index: true
            -
                name: end_date
                data_type: date
                index: true
            -
                name: firstname
                data_type: text
                index: true
            -
                name: lastname
                data_type: text
                index: true
            -
                name: padi
                data_type: text
                index: true
            -
                name: product
                data_type: text
                index: true
    -
        name: 'Pocket Card Job'
        field:
            -
                name: jobStatus
                text: 'Job Status'
                data_type: text
            -
                name: documents
                text: 'Pocket Card'
                data_type: document
    -
        name: 'Auto Renewal'
        field:
            -
                name: policyStatus
                text: 'Policy Status'
                data_type: text
                index: true
            -
                name: documents
                text: 'Policy Documents'
                data_type: document
            -
                name: start_date
                data_type: date
                index: true
            -
                name: end_date
                data_type: date
                index: true
            -
                name: firstname
                data_type: text
                index: true
            -
                name: lastname
                data_type: text
                index: true
            -
                name: padi
                data_type: text
                index: true
            -
                name: product
                data_type: text
                index: true
pages:
    -
        page_name: UserHomePage.yml
        uuid: c718e435-efc4-4677-ba72-4b8996b78a64
    -
        page_name: UserHistoryPage.yml
        uuid: e0a85518-7657-470f-92d8-00b3dea0bcf4
    -
        page_name: UserApprovalRequest.yml
        uuid: d3af6a0d-b680-4a68-ab3c-912ebd2bb391
    -
        page_name: CSRDashboardPage.yml
        uuid: 016a34e6-4af6-4863-b8e2-0cee142b09a2
    -
        page_name: CSRRequestsPage.yml
        uuid: 9b52ced7-80b7-4cd6-a986-d4df6812b139
    -
        page_name: ErrorHandlerPage.yml
        uuid: 3af8eeb0-7f43-422a-90f4-2b30b7aab9b7
    -
        page_name: CSRManagePolicyPage.yml
        uuid: a488af79-31ee-4f11-8715-5bec00f85c8d
    -
        page_name: CSRSearchPage.yml
        uuid: 38b1b9c7-0f6e-4e80-bb08-63262e56c2f9
    -
        page_name: VerifyPadiPage.yml
        uuid: 0c17785a-b7ae-46c4-a1c3-8bed234b4482
    -
        page_name: PocketCardPage.yml
        uuid: 11cd5446-c2fa-42cc-93b1-638670f4adf7
    -
        page_name: MyAssignmentsPage.yml
        uuid: 151ba91d-f17a-4034-a25f-86f108594637
    -
        page_name: ViewChangeLog.yml
        uuid: 121ba91d-f17a-2034-a25f-86f108594637
    -
        page_name: AdminPage.yml
        uuid: c869ce1d-022c-40b8-8214-86ba3d6442e4
menu:
    -
        name: Home
        privilege: '{"eq" : "MANAGE_MY_POLICY_WRITE","neq" : "MANAGE_POLICY_APPROVAL_READ"}'
        icon: 'fa fa-home'
        page_uuid: c718e435-efc4-4677-ba72-4b8996b78a64
        uuid: 7794c91e-b708-41be-83e1-cc0bb6cd667a
    -
        name: 'My History'
        privilege: '{"eq" : "MANAGE_MY_POLICY_READ","neq" : "MANAGE_POLICY_APPROVAL_READ"}'
        icon: 'fa fa-book'
        page_uuid: e0a85518-7657-470f-92d8-00b3dea0bcf4
        uuid: 623132d9-8ccb-4c8a-b7b7-a3b0921defdc
    -
        name: 'Approval Request'
        privilege: '{"eq" : "MANAGE_MY_POLICY_WRITE","neq" : "MANAGE_POLICY_APPROVAL_READ"}'
        icon: 'fa fa-list'
        page_uuid: d3af6a0d-b680-4a68-ab3c-912ebd2bb391
        uuid: 7794c91e-b708-41be-83e1-cc0bb6cd789e
    -
        name: Home
        icon: 'fa fa-home'
        privilege: MANAGE_POLICY_APPROVAL_READ
        page_uuid: 016a34e6-4af6-4863-b8e2-0cee142b09a2
        uuid: 24176975-8f4d-499d-8b2d-86902de26c14
    -
        name: Requests
        privilege: MANAGE_POLICY_APPROVAL_WRITE
        icon: 'fa fa-list'
        page_uuid: 9b52ced7-80b7-4cd6-a986-d4df6812b139
        uuid: 50fd8782-3e08-4a4c-9ff2-10d404904e5e
    -
        name: Errors
        privilege: MANAGE_DIVEINSURANCE_ERRORS_WRITE
        icon: 'fa fa-warning'
        page_uuid: 3af8eeb0-7f43-422a-90f4-2b30b7aab9b7
        uuid: 41551bff-e30e-4ba5-abc1-1a864f12e061
    -
        name: 'Manage Policies'
        icon: 'fa fa-folder-open'
        privilege: MANAGE_POLICY_APPROVAL_WRITE
        page_uuid: a488af79-31ee-4f11-8715-5bec00f85c8d
        uuid: 576f6ce4-74e6-11ea-bc55-0242ac130003
    -
        name: 'Search Policies'
        icon: 'fa fa-search'
        privilege: MANAGE_POLICY_APPROVAL_WRITE
        page_uuid: 38b1b9c7-0f6e-4e80-bb08-63262e56c2f9
        uuid: 3a4cc987-5627-4882-89ae-3bdc4f6e1e77
    -
        name: 'Verify PADI details'
        icon: 'fa fa-list-alt'
        privilege: MANAGE_POLICY_APPROVAL_READ
        page_uuid: 0c17785a-b7ae-46c4-a1c3-8bed234b4482
        uuid: 9bf92403-2111-4d05-9d89-01a609ed4b83
    -
        name: 'Pocket Card'
        privilege: MANAGE_POLICY_APPROVAL_WRITE
        icon: 'fa fa-address-card'
        page_uuid: 11cd5446-c2fa-42cc-93b1-638670f4adf7
        uuid: 7794c91e-b708-41be-83e1-cc0bb6cd669a
    -
        name: MyAssignments
        privilege: HIDE_FOR_NOW
        icon: 'fa fa-list'
        page_uuid: 151ba91d-f17a-4034-a25f-86f108594637
        uuid: 3b396d26-c0cb-4436-8804-f22431d6ac8c
    -
        name: Administrator
        privilege: MANAGE_ADMIN_WRITE
        icon: 'far fa-users-cog'
        page_uuid: c869ce1d-022c-40b8-8214-86ba3d6442e4
        uuid: d9cca9b1-dc90-4e34-9cf6-34e42706462c
workflow:
    -
        name: 'Individual Liability'
        uuid: f0efea9e-7863-4368-a9b2-baa1a1603067
        bpmn_file: 'Individual Professional Liability/NewUserApplicationSubmission.bpmn'
        entity: 'Individual Professional Liability'
    -
        name: 'Individual Liability Endorsement'
        uuid: 7d302209-667d-46e4-80f0-3dd1a4079509
        bpmn_file: 'Individual Professional Liability/IPLEndorsement.bpmn'
        entity: 'Individual Professional Liability'
    -
        name: 'Auto Renewal'
        uuid: 91cb9e10-5845-4379-97c9-f9486b702bd6
        bpmn_file: 'Individual Professional Liability/IPLAutoRenewal.bpmn'
        entity: 'Auto Renewal'
    -
        name: 'Emergency First Response'
        uuid: cb74d176-225a-11ea-978f-2e728ce88125
        bpmn_file: 'Emergency First Response/NewApplication.bpmn'
        entity: 'Emergency First Response'
    -
        name: 'Emergency First Response Endorsement'
        uuid: 35139ac6-3229-11ea-aec2-2e728ce88125
        bpmn_file: 'Emergency First Response/EFREndorsement.bpmn'
        entity: 'Emergency First Response'
    -
        name: 'Individual Liability Reinstate Policy'
        uuid: 81cb9e10-5845-4379-97c9-f9486b702bdb
        bpmn_file: 'Cancel Policy/ReinstatePolicyIPL.bpmn'
        entity: 'Individual Professional Liability'
    -
        name: 'Emergency First Response Reinstate Policy'
        entity: 'Emergency First Response'
        uuid: a484ac20-0bc6-4c3f-9426-199e6fadc4a2
        bpmn_file: 'Cancel Policy/ReinstatePolicyEFR.bpmn'
    -
        name: 'Dive Boat Reinstate Policy'
        entity: 'Dive Boat'
        uuid: 2d94a2f0-c64c-48e0-a4f0-f85f626f0626
        bpmn_file: 'Cancel Policy/ReinstatePolicyDB.bpmn'
    -
        name: 'Dive Store Reinstate Policy'
        entity: 'Dive Store'
        uuid: 5a2ed122-3f12-4240-b197-a24469721e87
        bpmn_file: 'Cancel Policy/ReinstatePolicyDS.bpmn'
    -
        bpmn_file: 'Cancel Policy/CancelPolicyIPL.bpmn'
        entity: 'Individual Professional Liability'
        name: 'IPL Cancel Policy'
        uuid: 71cb9e10-5845-4379-97c9-f9486b702bda
    -
        bpmn_file: 'Cancel Policy/CancelPolicyEFR.bpmn'
        entity: 'Emergency First Response'
        name: 'EFR Cancel Policy'
        uuid: 81cb9e10-5845-4379-97c9-f9486b702bda
    -
        bpmn_file: 'Cancel Policy/CancelPolicyDB.bpmn'
        entity: 'Dive Boat'
        name: 'DB Cancel Policy'
        uuid: 91cb9e10-5845-4379-97c9-f9486b702bda
    -
        bpmn_file: 'Cancel Policy/CancelPolicyDS.bpmn'
        entity: 'Dive Store'
        name: 'DS Cancel Policy'
        uuid: 61cb9e10-5845-4379-97c9-f9486b702bda
    -
        name: 'Dive Boat'
        uuid: bb15e393-11b9-48ea-bc5a-5b7616047cb1
        bpmn_file: 'Dive Boat/NewApplicationSubmission.bpmn'
        entity: 'Dive Boat'
    -
        name: 'Dive Boat Endorsement'
        uuid: 2bc1caaa-9628-486d-8b42-104534625993
        bpmn_file: 'Dive Boat/DiveBoatEndorsement.bpmn'
        entity: 'Dive Boat'
    -
        name: 'Dive Store'
        uuid: cb99e634-de00-468d-9230-d6f77d241c5b
        bpmn_file: 'Dive Store/NewApplication.bpmn'
        entity: 'Dive Store'
    -
        name: 'Dive Store Endorsement'
        uuid: 2bc1caaa-9628-486d-8b42-104534625994
        bpmn_file: 'Dive Store/DiveStoreEndorsement.bpmn'
        entity: 'Dive Store'
form:
    -
        name: 'PADI Verification'
        uuid: d2ed4200-9131-4671-b0e0-de3e27c3f610
        description: 'Page for CSR to verify PADI details'
        template_file: padiValidationPage.json
        entity: Padi
    -
        name: 'Pocket Card'
        uuid: e2ed4200-9131-4671-b0e0-de3e27c3f611
        description: 'Lets CSR generate and view Pocket Cards'
        template_file: pocketCard.json
        entity: 'Pocket Card Job'
job:
    -
        uuid: 5acf3bbb-4daf-4257-9931-cb7ccfcc1e03
        name: 'Expired Policy Status Update 1'
        url: /app/d77ea120-b028-479b-8c6e-60476b6a4456/delegate/UpdatePolicyStatusOnExpiration
        cron: '0 30 9 1 JUL ? *'
        data:
            flag: notEqualTo
            orgId: f0033dc0-126b-40ba-89e0-d3061bdeda4c
            appId: d77ea120-b028-479b-8c6e-60476b6a4456
    -
        uuid: 5903b164-59d2-4841-ae30-e7891f7445c5
        name: 'Expired Policy Status Update 2'
        url: /app/d77ea120-b028-479b-8c6e-60476b6a4456/delegate/UpdatePolicyStatusOnExpiration
        cron: '0 30 9 23 JUL ? *'
        data:
            flag: equalTo
            orgId: f0033dc0-126b-40ba-89e0-d3061bdeda4c
            appId: d77ea120-b028-479b-8c6e-60476b6a4456
