app:
    -
        name: DiveInsurance
        uuid: d77ea120-b028-479b-8c6e-60476b6a4456
        description: 'App for Dive Insurance'
        category: EXAMPLE_CATEGORY
        type: 2
        autostart: true
org:
    -
        name: 'Vincencia & Buckley'
        uuid: f0033dc0-126b-40ba-89e0-d3061bdeda4c
        email: testhub07@gmail.com
        address1: '6 bCenterpoint'
        address2: Dr.
        city: 'La Palma'
        state: CA
        zip: 90623
        country: 'United States'
        contact:
            username: testhub07.gmail.com
            firstname: Admin
            lastname: User
            email: testhub07@gmail.com
        preferences: '{}'
privilege:
    -
        name: MANAGE_POLICY_APPROVAL
        permission: 3
    -
        name: MANAGE_MY_POLICY
        permission: 3
    -
        name: MANAGE_DIVEINSURANCE_ERRORS
        permission: 3
role:
    -
        name: 'Policy Holder'
        default: true
        privileges:
            -
                privilege_name: MANAGE_MY_POLICY
                permission: 3
        uuid: bf349be5-3d33-45bf-84a9-816b712002f4
menu:
    -
        name: Home
        uuid: e1ee3006-77a7-4d62-ad25-b7be66387fb1
        privilege: MANAGE_MY_POLICY_WRITE
        icon: 'fa fa-home'
        page:
            name: 'My Policies'
            description: 'Shows a list of users policies'
            content:
                -
                    type: Document
                    content: '<p><h2>Personal Policies</h2></p><p></p>'
                -
                    type: List
                    content:
                        route: file
                        filterable: true
                        reorderable: true
                        resizable: true
                        pageable:
                            buttonCount: 3
                            pageSizes:
                                - 10
                                - 20
                                - 50
                            info: true
                        actions:
                            -
                                name: View
                                page_id: 1
                                icon: 'fa fa-envelope-open'
                            -
                                name: Cancel
                                page_id: 3
                                icon: 'fa fa-window-close'
                        operations:
                            title: 'Create Policies'
                            actions:
                                -
                                    name: IPL
                                    rule: 'true'
                                    details: [{ type: Form, url: workflow/9619673a-8e6b-4b98-866f-a90e40eeb5e8/startform }]
                                -
                                    name: 'Dive Boat'
                                    rule: 'true'
                                    details: [{ type: Form, url: workflow/9619673a-8e6b-4b98-866f-a90e40eeb5e8/startform }]
                                -
                                    name: 'Dive Store'
                                    rule: 'true'
                                    details: [{ type: Form, url: workflow/9619673a-8e6b-4b98-866f-a90e40eeb5e8/startform }]
                        columnConfig:
                            -
                                title: Name
                                field: name
                            -
                                title: Status
                                field: status
                            -
                                title: Data
                                field: data
    -
        name: 'My History'
        uuid: c420e935-372a-44e2-b4d7-4979439f9427
        privilege: MANAGE_MY_POLICY_READ
        icon: 'fa fa-table'
        page:
            name: 'All Policies'
            description: 'Shows all the policies'
            content:
                -
                    type: List
                    content:
                        route: file
                        filterable: true
                        reorderable: true
                        resizable: true
                        sortable: true
                        pageable:
                            buttonCount: 3
                            pageSizes:
                                - 10
                                - 20
                                - 50
                            info: true
                        columnConfig:
                            -
                                title: PADI
                                field: padi
                            -
                                title: 'First Name'
                                field: firstname
                            -
                                title: 'Last Name'
                                field: lastname
                            -
                                title: Product
                                field: workflow_name
                            -
                                title: Task
                                field: activityName
                            -
                                title: 'Submission Date'
                                field: start_date
    -
        name: Home
        icon: 'fa fa-home'
        privilege: MANAGE_POLICY_APPROVAL_READ
        page:
            name: Dashboard
            description: 'Shows dashboard'
            content:
                -
                    type: Dashboard
                    dashboard: Dashboard
        uuid: dc280f97-f4f7-4fb1-ac56-e820831445c3
    -
        name: Requests
        privilege: MANAGE_POLICY_APPROVAL_WRITE
        icon: 'fa fa-list'
        page:
            name: Requests
            description: 'Shows requests'
            content:
                -
                    type: List
                    content:
                        route: assignments
                        filterable: true
                        reorderable: true
                        resizable: true
                        sortable: true
                        pageable:
                            buttonCount: 3
                            pageSizes:
                                - 10
                                - 20
                                - 50
                            info: true
                        operations:
                            title: 'Create Policies'
                            actions:
                                -
                                    name: IPL
                                    rule: 'true'
                                    details: [{ type: Form, url: workflow/f0efea9e-7863-4368-a9b2-baa1a1603067/startform }]
                                -
                                    name: 'Dive Store'
                                    rule: 'true'
                                    details: [{ type: Form, url: workflow/cb99e634-de00-468d-9230-d6f77d241c5b/startform }]
                                -
                                    name: 'Dive Boat'
                                    rule: 'true'
                                    details: [{ type: Form, url: workflow/bb15e393-11b9-48ea-bc5a-5b7616047cb1/startform }]
                                -
                                    name: 'Emergency First Response'
                                    rule: 'true'
                                    details: [{ type: Form, url: workflow/9619673a-8e6b-4b98-866f-a90e40eeb5e8/startform }]
                        actions:
                            -
                                name: Approve
                                rule: '{{to_be_claimed}} == 1'
                                details:
                                    - { type: Update, params: { url: 'workflowinstance/{{workflowInstanceId}}/activityinstance/{{activityInstanceId}}/claim' } }
                                    - { type: Form, url: 'workflowinstance/{{workflowInstanceId}}/activityinstance/{{activityInstanceId}}/form' }
                                icon: 'fa fa-check-circle'
                            -
                                name: Approve
                                rule: '{{to_be_claimed}} == 0'
                                details:
                                    - { type: Form, url: 'workflowinstance\/{{workflowInstanceId}}\/activityinstance\/{{activityInstanceId}}\/form' }
                                icon: 'fa fa-check-circle'    
                        columnConfig:
                            -
                                title: PADI
                                field: padi
                            -
                                title: 'First Name'
                                field: firstname
                            -
                                title: 'Last Name'
                                field: lastname
                            -
                                title: Product
                                field: workflow_name
                            -
                                title: Task
                                field: activityName
                            -
                                title: 'Submission Date'
                                field: start_date
        uuid: 452287d9-86ea-4dd1-b18a-53bf9a924d1a
    -
        name: Errors
        privilege: MANAGE_DIVEINSURANCE_ERRORS_WRITE
        icon: 'fa fa-warning'
        page:
            name: Errors
            description: 'Shows errors which occured in workflow'
            content:
                -
                    type: List
                    content:
                        route: errorlog
                        filterable: true
                        reorderable: true
                        resizable: true
                        sortable: true
                        pageable:
                            buttonCount: 3
                            pageSizes:
                                - 10
                                - 20
                                - 50
                            info: true
                        actions:
                            -
                                name: retry
                                rule: 'true'
                                details:
                                    - { type: Update, params: { url: 'errorlog/{{id}}/retry' } }
                        columnConfig:
                            -
                                title: Id
                                field: id
                            -
                                title: 'Type of Error'
                                field: error_type
                            -
                                title: Data
                                field: payload
                            -
                                title: 'Date Created'
                                field: date_created
                            -
                                title: Parameters
                                field: params
        uuid: b2cb5a1e-93b1-4263-b097-9a98c5d35d33
    -
        name: 'Manage Policies'
        icon: 'fa fa-list-alt'
        privilege: MANAGE_POLICY_APPROVAL_WRITE
        page:
            name: 'Manage Policies'
            description: 'Page to manage policies'
            content:
                -
                    type: Search
                    content:
                        actions:
                            -
                                name: View
                                page_id: 1
                                icon: 'fa fa-envelope-open'
                            -
                                name: Cancel
                                page_id: 3
                                icon: 'fa fa-window-close'
                        filterColumns:
                            - name
                            - padi
                            - firstname
                            - lastname
                        operations:
                            title: 'Create Policies'
                            actions:
                                -
                                    name: IPL
                                    rule: 'true'
                                    details: [{ type: Form, url: workflow/9619673a-8e6b-4b98-866f-a90e40eeb5e8/startform }]
                                -
                                    name: 'Dive Boat'
                                    rule: 'true'
                                    details: [{ type: Form, url: workflow/9619673a-8e6b-4b98-866f-a90e40eeb5e8/startform }]
                                -
                                    name: 'Dive Store'
                                    rule: 'true'
                                    details: [{ type: Form, url: workflow/9619673a-8e6b-4b98-866f-a90e40eeb5e8/startform }]
                        columnConfig:
                            -
                                title: Name
                                field: name
                            -
                                title: Status
                                field: status
        uuid: cb7a2022-307f-40ff-88dc-64d6d5834f5c
    -
        name: 'Verify PADI details'
        icon: 'fa fa-search'
        page:
            name: 'Verify PADI details'
            description: 'Lets CSR to input and check PADI Data'
            content:
                -
                    content: '<h3>Verify PADI Details</h3>'
                    type: Document
                -
                    formUuid: d2ed4200-9131-4671-b0e0-de3e27c3f610
                    type: Form
        uuid: 40209052-2550-4d60-a2ea-7a38bb614c7a    
workflow:
    -
        name: 'Individual Liability'
        uuid: f0efea9e-7863-4368-a9b2-baa1a1603067
        bpmn_file: 'Individual Professional Liability/NewUserApplicationSubmission.bpmn'
        entity: 'Individual Professional Liability'
    -
        name: 'Dive Store'
        uuid: cb99e634-de00-468d-9230-d6f77d241c5b
        bpmn_file: 'Dive Store/NewApplication.bpmn'
        entity: 'Dive Store'
    -
        name: 'Dive Boat'
        uuid: bb15e393-11b9-48ea-bc5a-5b7616047cb1
        bpmn_file: 'Dive Boat/NewApplicationSubmission.bpmn'
        entity: 'Dive Boat'
    -
        name: 'Individual Liability Auto Renewal'
        uuid: 91cb9e10-5845-4379-97c9-f9486b702bd6
        bpmn_file: 'Individual Professional Liability/IPLAutoRenewal.bpmn'
        entity: 'Individual Professional Liability'
form:
    -
        name: 'PADI Verification'
        uuid: d2ed4200-9131-4671-b0e0-de3e27c3f610
        description: 'Page for CSR to verify PADI details'
        template: padi_validation.json
        entity: Padi
job:
    -
        import_padi:
            -
                stored_procedure_name: ox_padi_verification
                upload_host_name: 206.107.76.164
                upload_host_user: vbinsurance
                upload_user_password: '<<InsureName>>'
