app:
    name: RISCOMInsurance
    title: 'RISCOM Insurance'
    description: 'Insurance OI Application'
    category: Dashboards
    type: 2
    autostart: 'false'
    uuid: 33f335b9-ceb9-4fd6-b51e-b4911eece839
    isdefault: false
    logo: default_app.png
    status: 4
    start_options: null
checkOrg: true
org:
    name: RISCOM
    uuid: 8396d782-d9a1-40d2-abf0-b291b8ff75f4
    email: riscom@vantageagora.com
    address1: '333 Texas Street, Suite 1150'
    address2: 'Shreveport, Louisiana 71101'
    city: Shreveport
    state: Louisiana
    zip: 71101
    contact:
        username: riscominsurer
        firstname: Riscom
        lastname: Insurer
        email: riscominsurer@vantageagora.com
    preferences: '{"dateformat":"MM-dd-yyyy","currency":"USD","timezone":"America/New_York"}'
    country: 'United States of America'
privilege:
    -
        name: MANAGE_RISCOMAGENT
        permission: 15
    -
        name: MANAGE_RISCOMUNDERWRITER
        permission: 15
    -
        name: MANAGE_RISCOMPRODUCTION
        permission: 15
role:
    -
        name: 'RISCOM Agent'
        privilegesDuplicate:
            -
                privilege_name:
                    name: MANAGE_RISCOMAGENT
                    permission: 15
                permission: 15
        default: true
        privileges:
            -
                privilege_name: MANAGE_RISCOMAGENT
                permission: 15
        uuid: 6f49ed69-310e-4a63-8118-9eb4276531f1
    -
        name: 'RISCOM Underwriter'
        privilegesDuplicate:
            -
                privilege_name:
                    name: MANAGE_RISCOMUNDERWRITER
                    permission: 15
                permission: 15
        default: true
        privileges:
            -
                privilege_name: MANAGE_RISCOMUNDERWRITER
                permission: 15
        uuid: a2068d7f-b556-4cca-a30e-23c3d3b6a8ab
    -
        name: 'RISCOM Production'
        privilegesDuplicate:
            -
                privilege_name:
                    name: MANAGE_RISCOMPRODUCTION
                    permission: 15
                permission: 15
        default: true
        privileges:
            -
                privilege_name: MANAGE_RISCOMPRODUCTION
                permission: 15
        uuid: 593b66d8-80ef-49ed-9349-537466273e7a
pages:
    -
        page_name: RISCOMManagerAgentOIPage.yml
        uuid: 99c8efa0-c42e-4a6e-b94e-8aa29835b687
    -
        page_name: RISCOMManagerUnderwriterOIPage.yml
        uuid: d5246917-6bd8-4821-8829-7f9e1bb01825
    -
        page_name: RISCOMManagerProductionOIPage.yml
        uuid: 32e74d3d-97c4-4b56-88b7-a9b11cf6ee59
menu:
    -
        name: Agent
        icon: 'fal fa-address-card'
        privilege: MANAGE_RISCOMAGENT_WRITE
        page_uuid: 99c8efa0-c42e-4a6e-b94e-8aa29835b687
        uuid: 27ff522d-4d63-4312-940f-a99d720f61c9
    -
        name: Underwriter
        icon: 'fas fa-user-edit'
        privilege: MANAGE_RISCOMUNDERWRITER_WRITE
        page_uuid: d5246917-6bd8-4821-8829-7f9e1bb01825
        uuid: ea4368d2-f5e7-48c9-bd0a-9e02c5ca84eb
    -
        name: Production
        icon: 'fal fa-funnel-dollar'
        privilege: MANAGE_RISCOMPRODUCTION_WRITE
        page_uuid: 32e74d3d-97c4-4b56-88b7-a9b11cf6ee59
        uuid: f7402ebc-995a-49c7-838a-58880a261b65
