app:
    -
        name: InsuranceOI
        uuid: f726fded-0764-4f4e-945e-689586baf74b
        description: 'Insurance OI Application'
        category: Dashboards
        type: 2
        autostart: 'true'
org:
    -
        name: 'EOX Vantage1'
        uuid: b0923de7-0387-48ea-8f29-5d3704d96a46
        email: helpdesk@vantageagora.com
        address1: '23611 Chagrin Blvd, Ste 320, Beachwood, Ohio 44122'
        address2: ''
        city: Beachwood
        state: OH
        zip: 44122
        contact:
            username: supportadmin
            firstname: Support
            lastname: Admin
            email: helpdesk@vantageagora.com
            phone: ''
        preferences:
            currency: USD
            timezone: America/New_York
            dateformat: mm/dd/yy
        country: 'United States'
privilege:
    -
        name: MANAGE_AGENTVIEW
        permission: 15
    -
        name: MANAGE_MANAGERVIEW
        permission: 15
role:
    -
        name: 'Insurance Agent'
        default: true
        privileges:
            -
                privilege_name: MANAGE_AGENTVIEW
                permission: 15
        uuid: c066efa8-09d4-4fc5-b5c3-89024becec86
    -
        name: 'Insurance Manager'
        default: true
        privileges:
            -
                privileges_name: MANAGE_MANAGERVIEW
                permission: 15
        uuid: a6745b11-9aa4-45f1-81c2-92deaba95171
menu:
    -
        name: Production
        icon: 'fa fa-home'
        privilege: MANAGE_MANAGERVIEW_WRITE
        page_name: ManagerProductionOIPage.yml
        uuid: d02ffb8f-a3ae-476a-a85f-198dd73359ac
    -
        name: Underwriter
        icon: 'fa fa-book'
        privilege: MANAGE_MANAGERVIEW_WRITE
        page_name: ManagerUnderwriterOIPage.yml
        uuid: 234e4f1b-1e44-40f3-a944-3a9b89d855a5
    -
        name: Agent
        icon: 'fa fa-book'
        privilege: MANAGE_MANAGERVIEW_WRITE
        page_name: ManagerAgentOIPage.yml
        uuid: 775f784d-0f25-4fab-85ef-c8b0a0832339