app:
    -
        name: AXONInsurance
        description: 'Insurance OI Application'
        category: Dashboards
        type: 2
        autostart: 'true'
        uuid: 648ddff8-71b7-4fe0-ac94-eeab5ad56e58
        isdefault: false
        logo: default_app.png
        status: 4
        start_options: null
org:
    -
        name: AXON
        uuid: c1daf39b-e7ec-42eb-b53f-b4affff82ac0
        email: axon@vantageagora.com
        address1: '198 W. High St.'
        address2: 'Somerville, NJ 08876'
        city: Somerville
        state: NJ
        zip: 08876
        contact:
            username: axoninsurer
            firstname: AXON
            lastname: Insurer
            email: axoninsurer@vantageagora.com
        preferences: '{"dateformat":"MM-dd-yyyy","currency":"USD","timezone":"America/New_York"}'
        country: 'United States'
privilege:
    -
        name: MANAGE_AXONAGENT
        permission: 15
    -
        name: MANAGE_AXONUNDERWRITER
        permission: 15
    -
        name: MANAGE_AXONPRODUCTION
        permission: 15
role:
    -
        name: 'AXON Agent'
        default: true
        privileges:
            -
                privilege_name: MANAGE_AXONAGENT
                permission: 15
        uuid: dc9a9183-2bb4-4b71-8a07-4d804584df86
    -
        name: 'AXON Underwriter'
        default: true
        privileges:
            -
                privilege_name: MANAGE_AXONUNDERWRITER
                permission: 15
        uuid: 577ae514-e6d2-4d04-a96a-2ee6ff3446ec
    -
        name: 'AXON Production'
        default: true
        privileges:
            -
                privilege_name: MANAGE_AXONPRODUCTION
                permission: 15
        uuid: fbe2e782-1327-4c08-90a9-6cb8bafecf12
pages:
    -
        page_name: AXONManagerAgentOIPage.yml
        uuid: a603084e-f94f-4997-aa26-b00c931a1a0c
    -
        page_name: AXONManagerUnderwriterOIPage.yml
        uuid: 4044c80f-4d63-45ee-a447-16f49ac88272
    -
        page_name: AXONManagerProductionOIPage.yml
        uuid: f233f565-0b61-4ec8-8090-0189441879d2
menu:
    -
        name: Agent
        icon: 'fal fa-address-card'
        privilege: MANAGE_AXONAGENT_WRITE
        page_uuid: a603084e-f94f-4997-aa26-b00c931a1a0c
        uuid: 18d3e6bb-e948-48e6-b27c-3a00bcee17b8
    -
        name: Underwriter
        icon: 'fad fa-user-edit'
        privilege: MANAGE_AXONUNDERWRITER_WRITE
        page_uuid: 4044c80f-4d63-45ee-a447-16f49ac88272
        uuid: 9e221c20-d33d-40a4-b8b3-d523e7e145e6
    -
        name: Production
        icon: 'fal fa-funnel-dollar'
        privilege: MANAGE_AXONPRODUCTION_WRITE
        page_uuid: f233f565-0b61-4ec8-8090-0189441879d2
        uuid: 078ce17c-a104-434c-ad71-f69a1a8331c8
