ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN TEXT_ TEXT;
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN TEXT_ TEXT;
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN TEXT_ TEXT;
UPDATE ACT_GE_PROPERTY SET VALUE_ = 0 WHERE NAME_ = "historyLevel";