version: '3'

services:
  mysql-5.7:
    image: mysql:5.7.35
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/sql
      - ./scripts:/scripts
    expose: 
      - '3306'
  phpmyadmin:
    depends_on:
      - mysql-5.7
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql-5.7
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    ports:
      - '8082:80'
volumes:
  mysql-data:
