# "#" this is a comment
#This is a docker-compose file to start Camel service 

#specifying version according to docker engine release version.
#refer to https://docs.docker.com/compose/compose-file/
version: "3.5"

#making sevices
services:
        camel:
                build:
                        context: ./docker
                        dockerfile: Dockerfile

                network_mode: "host"
                volumes:
                          - ".:/workspace/app"
                          - "../../:/app"
                labels:
                        com.oxapp.description: "Apache Activemq/Camel"