version: '3.5'
services:
    camel:
        build:
            context: ./docker
            args:
                HOST: ${HOST}
        network_mode: "host"    
        ports:
            - "8161:8161"
            - "8085:8085"
        volumes:
            - ./:/workspace/app
            - ../../:/app      