version: '3.5'
services:
    camel:
        build:
            context: ./docker
            args:
                HOST: ${HOST}
        network_mode: "host"    
        ports:
            - "8161:8161"
            - "8085:8085"
            - "61616:61616"
            - "5672:5672"
            - "61613:61613"
            - "1883:1883"
            - "61614:61614"
        volumes:
            - ./:/workspace/app
            - ../../:/app      