app:
    -
        name: HIIGInsurance
        uuid: 5c94711c-47ec-4687-b3a8-ade7e3ac404b
        description: 'Insurance OI Application'
        category: Dashboards
        type: 2
        autostart: 'true'
org:
    -
        name: 'HIIG'
        uuid: d5cf6f2b-5384-4fbe-99b2-b787a557cd50
        email: hiig@vantageagora.com
        address1: '800 Gessner Rd'
        address2: 'Houston	TX 77024'
        city: Houston
        state: TX
        zip: 77024
        contact:
            username: hiiginsurer
            firstname: HIIG
            lastname: Insurer
            email: hiiginsurer@vantageagora.com
        preferences: '{"dateformat":"MM-dd-yyyy","currency":"USD","timezone":"America/New_York"}'
        country: 'United States'
privilege:
    -
        name: MANAGE_HOSPITALITYAGENT
        permission: 15
    -
        name: MANAGE_HOSPITALITYUNDERWRITER
        permission: 15
    -
        name: MANAGE_HOSPITALITYPRODUCTION
        permission: 15
    -
        name: MANAGE_PESTAGENT
        permission: 15
    -
        name: MANAGE_PESTUNDERWRITER
        permission: 15
    -
        name: MANAGE_PESTPRODUCTION
        permission: 15
    -
        name: MANAGE_REGTAGENT
        permission: 15
    -
        name: MANAGE_REGTUNDERWRITER
        permission: 15
    -
        name: MANAGE_REGTPRODUCTION
        permission: 15
    -
        name: MANAGE_TIMBERSUREAGENT
        permission: 15
    -
        name: MANAGE_TIMBERSUREUNDERWRITER
        permission: 15
    -
        name: MANAGE_TIMBERSUREPRODUCTION
        permission: 15
role:
    -
        name: 'Hospitality Agent'
        default: true
        privileges:
            -
                privilege_name: MANAGE_HOSPITALITYAGENT
                permission: 15
        uuid: c6a1a908-f957-4eb8-beb5-3b4e8232c5f4
    -
        name: 'Hospitality Underwriter'
        default: true
        privileges:
            -
                privilege_name: MANAGE_HOSPITALITYUNDERWRITER
                permission: 15
        uuid: 574ff8ad-805a-4d6b-86f6-5eb818c8ff7c
    -
        name: 'Hospitality Production'
        default: true
        privileges:
            -
                privilege_name: MANAGE_HOSPITALITYPRODUCTION
                permission: 15
        uuid: c0ed3553-d866-4c97-b15e-9cc996bdf0bd
    -
        name: 'PEST Agent'
        default: true
        privileges:
            -
                privilege_name: MANAGE_PESTAGENT
                permission: 15
        uuid: b67a1522-1648-4562-87a8-074ef752d805
    -
        name: 'PEST Underwriter'
        default: true
        privileges:
            -
                privilege_name: MANAGE_PESTUNDERWRITER
                permission: 15
        uuid: c8f0130c-5ade-4d17-ad35-90f4de5ad40b
    -
        name: 'PEST Production'
        default: true
        privileges:
            -
                privilege_name: MANAGE_PESTPRODUCTION
                permission: 15
        uuid: 76c71f76-eb17-4638-bbe9-b178540665a3
    -
        name: 'REGT Agent'
        default: true
        privileges:
            -
                privilege_name: MANAGE_REGTAGENT
                permission: 15
        uuid: c81c1d0b-29de-4c80-bc5e-9c1596f95cee
    -
        name: 'REGT Underwriter'
        default: true
        privileges:
            -
                privilege_name: MANAGE_REGTUNDERWRITER
                permission: 15
        uuid: 201970f4-3c5c-4138-b6c4-849bafdfeb3d
    -
        name: 'REGT Production'
        default: true
        privileges:
            -
                privilege_name: MANAGE_REGTPRODUCTION
                permission: 15
        uuid: 66bf2143-e4e0-4597-bf15-a04df35a5938
    -
        name: 'TIMBERSURE Agent'
        default: true
        privileges:
            -
                privilege_name: MANAGE_TIMBERSUREAGENT
                permission: 15
        uuid: 3008774e-a637-41ac-8939-74eabb10c03f
    -
        name: 'TIMBERSURE Underwriter'
        default: true
        privileges:
            -
                privilege_name: MANAGE_TIMBERSUREUNDERWRITER
                permission: 15
        uuid: 9ab797b5-036e-4152-932f-4f778e6f8cf7
    -
        name: 'TIMBERSURE Production'
        default: true
        privileges:
            -
                privilege_name: MANAGE_TIMBERSUREPRODUCTION
                permission: 15
        uuid: 77e14aba-e72e-4e00-917d-b49daee7185a
pages:
    -
        page_name: HospitalityManagerAgentOIPage.yml
        uuid: bfa5901c-0379-42cb-9086-4879761e4b2c
    -
        page_name: HospitalityManagerUnderwriterOIPage.yml
        uuid: 28a3dad1-2f22-4745-99ff-4507921e3391
    -
        page_name: HospitalityManagerProductionOIPage.yml
        uuid: 6f3eec0f-cd45-4df8-aaab-8983d3ccb915
    -
        page_name: PESTManagerAgentOIPage.yml
        uuid: f8be8129-6c22-40b0-b4e9-7245a952c97c
    -
        page_name: PESTManagerUnderwriterOIPage.yml
        uuid: 38f63377-e070-42cc-bb22-b9a229f4b0f7
    -
        page_name: PESTManagerProductionOIPage.yml
        uuid: 79a06ce7-2c9f-47cf-a21d-e1536e90fac3
    -
        page_name: REGTManagerAgentOIPage.yml
        uuid: aa9b4afa-0241-40fb-896e-83a1c5052a31
    -
        page_name: REGTManagerUnderwriterOIPage.yml
        uuid: 784f75da-a8e4-4874-a956-cef3924d6f98
    -
        page_name: REGTManagerProductionOIPage.yml
        uuid: 6914f763-ec49-42a5-a985-7074785b3b65
    -
        page_name: TimberManagerAgentOIPage.yml
        uuid: 3d785b2b-007d-4c72-a2bb-f9112d35d78d
    -
        page_name: TimberManagerUnderwriterOIPage.yml
        uuid: 1d4a2ab2-9e45-4711-bfbb-cd9c853c88c0
    -
        page_name: TimberManagerProductionOIPage.yml
        uuid: 638ee3cc-9ac2-45b0-8301-126d0f7b7896
menu:
    -
        name: Hospitality Agent
        icon: 'fal fa-address-card'
        privilege: MANAGE_HOSPITALITYAGENT_WRITE
        page_uuid: bfa5901c-0379-42cb-9086-4879761e4b2c
        uuid: cae86177-9fb1-4894-89bd-5e24ddf31180
    -
        name: Hospitality Underwriter
        icon: 'fad fa-user-edit'
        privilege: MANAGE_HOSPITALITYUNDERWRITER_WRITE
        page_uuid: 28a3dad1-2f22-4745-99ff-4507921e3391
        uuid: 9a6330d9-11e8-454a-9534-74514c058333
    -
        name: Hospitality Production
        icon: 'fal fa-funnel-dollar'
        privilege: MANAGE_HOSPITALITYPRODUCTION_WRITE
        page_uuid: 6f3eec0f-cd45-4df8-aaab-8983d3ccb915
        uuid: e3fe56dc-0e4d-4a00-a3e8-7e95ff86db38
    -
        name: PEST Agent
        icon: 'fal fa-address-card'
        privilege: MANAGE_PESTAGENT_WRITE
        page_uuid: f8be8129-6c22-40b0-b4e9-7245a952c97c
        uuid: 54b0fa76-1d04-40f4-b0fd-8b6961ba47d6
    -
        name: PEST Underwriter
        icon: 'fad fa-user-edit'
        privilege: MANAGE_PESTUNDERWRITER_WRITE
        page_uuid: 38f63377-e070-42cc-bb22-b9a229f4b0f7
        uuid: 3579e745-8f35-42d2-84ef-d17c14a04ceb
    -
        name: PEST Production
        icon: 'fal fa-funnel-dollar'
        privilege: MANAGE_PESTPRODUCTION_WRITE
        page_uuid: 79a06ce7-2c9f-47cf-a21d-e1536e90fac3
        uuid: da71e093-e2f8-4b9f-932b-f57b938bf35b
    -
        name: REGT Agent
        icon: 'fal fa-address-card'
        privilege: MANAGE_REGTAGENT_WRITE
        page_uuid: aa9b4afa-0241-40fb-896e-83a1c5052a31
        uuid: 674d585f-a8e2-4940-80dd-ee1c9db312c8
    -
        name: REGT Underwriter
        icon: 'fad fa-user-edit'
        privilege: MANAGE_REGTUNDERWRITER_WRITE
        page_uuid: 784f75da-a8e4-4874-a956-cef3924d6f98
        uuid: 43b6b3c7-4321-4f30-b620-64f514c2e029
    -
        name: REGT Production
        icon: 'fal fa-funnel-dollar'
        privilege: MANAGE_REGTPRODUCTION_WRITE
        page_uuid: 6914f763-ec49-42a5-a985-7074785b3b65
        uuid: 5657e8af-4ff2-4ea7-9828-c2cc0fab96bb
    -
        name: TimberSure Agent
        icon: 'fal fa-address-card'
        privilege: MANAGE_TIMBERSUREAGENT_WRITE
        page_uuid: 3d785b2b-007d-4c72-a2bb-f9112d35d78d
        uuid: 80850512-859d-45e9-ae71-d188c9fb6dd3
    -
        name: TimberSure Underwriter
        icon: 'fad fa-user-edit'
        privilege: MANAGE_TIMBERSUREUNDERWRITER_WRITE
        page_uuid: 1d4a2ab2-9e45-4711-bfbb-cd9c853c88c0
        uuid: 310b4bd7-56b4-4d76-a916-bd40f49e691e
    -
        name: TimberSure Production
        icon: 'fal fa-funnel-dollar'
        privilege: MANAGE_TIMBERSUREPRODUCTION_WRITE
        page_uuid: 638ee3cc-9ac2-45b0-8301-126d0f7b7896
        uuid: 27cd9628-0ada-4578-9373-43a6d9fd45d1